#!/bin/bash

format() {
    venv/bin/python -m isort .
    venv/bin/python -m black .
}

push() {
    format
    git status --short
    printf "Are you sure you want to push? (y/n) "
    read -r answer
    if $(echo "$answer" | grep -iq "^y"); then
        git add .
        git commit
        git push origin $(git branch --show-current)
    fi
}

test() {
    format
    source venv/bin/activate
    venv/bin/python -m coverage run -m pytest
    venv/bin/python -m coverage report -m
}

setup-dev() {
    /usr/bin/python3 -m venv -h > /dev/null 2>&1 || sudo apt install python3-venv
    rm -rf venv
    /usr/bin/python3 -m venv venv
    venv/bin/python -m pip install -r requirements-dev.txt
    venv/bin/python -m pip install -r requirements.txt
}

start-dev() {
    format
    venv/bin/python -m uvicorn main:app --reload --port 8080 --host localhost
}

$@